blank_issues_enabled: false
contact_links:
  - name: Ask a Question
    url: mailto:vivek.kr96@outlook.com
    about: Feel free to send me an email —
      whether it’s a question, a private bug report, or just some feedback. I’ll try to respond soon!